//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingAlgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualTransactions
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string StartingLABUPrice { get; set; }
        public string StartingLABDPrice { get; set; }
        public string Strategy { get; set; }
        public string StartingType { get; set; }
        public Nullable<int> Shares { get; set; }
        public string EndingLABUPrice { get; set; }
        public string EndingLABDPrice { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public string ActualLABUStartingPrice { get; set; }
        public string ActualLABDStartingPrice { get; set; }
        public string ActualLABUEndingPrice { get; set; }
        public string ActualLABDEndingPrice { get; set; }
        public string EndDate { get; set; }
    }
}
