//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingAlgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosingPosition
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string LABUPrice { get; set; }
        public string LABDPrice { get; set; }
        public string LimitPrice { get; set; }
        public string Strategy { get; set; }
        public string Type { get; set; }
        public string mapping { get; set; }
        public Nullable<int> Shares { get; set; }
        public string Reason { get; set; }
    }
}
