//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingAlgo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AlpacaEntities : DbContext
    {
        public AlpacaEntities()
            : base("name=AlpacaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClosingPosition> ClosingPosition { get; set; }
        public virtual DbSet<LABU> LABU { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<StartingPosition> StartingPosition { get; set; }
        public virtual DbSet<ActualTransactions> ActualTransactions { get; set; }
        public virtual DbSet<LABD> LABD { get; set; }
        public virtual DbSet<Allocations> Allocations { get; set; }
        public virtual DbSet<JNUG> JNUG { get; set; }
    
        public virtual int apGetLastClosingPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("apGetLastClosingPrice");
        }
    
        public virtual ObjectResult<apGetTransactions_Result> apGetTransactions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<apGetTransactions_Result>("apGetTransactions");
        }
    
        public virtual ObjectResult<apGetTrades_Result> apGetTrades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<apGetTrades_Result>("apGetTrades");
        }
    
        public virtual ObjectResult<apGetTransactions1_Result> apGetTransactions1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<apGetTransactions1_Result>("apGetTransactions1");
        }
    
        public virtual ObjectResult<GetTrades_Result> GetTrades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTrades_Result>("GetTrades");
        }
    }
}
